PROVIDERS = ['openweather', 'weatherapi', 'weatherbit']
UNITS = ['K', 'F', 'C']
GETABLE_COLUMN_NAMES = ['temperature', 'humidity', 'weather', 'date', 'all']
ORDER_IN = ['ASC', 'DSC']
COLUMN_NAMES = ['id', 'city', '"temperature (K)"', '"humidity (%)"', 'weather', 'date', 'time']